#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions


rm -rf processor*
cleanCase
rm -rf 0
rm -rf zz*
###rm Remaining_Snow_On_Patches_Summary*
rm constant/polyMesh/boundary > /dev/null 2>&1

#------------------------------------------------------------------------------
